### ISSUE TITLE
metrics: generate grpc-gateway related files and structs

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-proto#204]
The Trace endpoint allows sending data serialized as JSON to the agent. There are many cases where folks want to also serialize metrics coming say from a front-end or a spot that doesn't use grpc nor protobufs so let's add support for metrics too.

**Comment by odeke-em** [comment]
I believe it would entail adding
```yaml
# This is an API configuration to generate an HTTP/JSON -> gRPC gateway for the
# OpenCensus service using github.com/grpc-ecosystem/grpc-gateway.
type: google.api.Service
config_version: 3
http:
 rules:
 - selector: opencensus.proto.agent.metrics.v1.MetricsService.Export
   post: /v1/metrics
   body: "*"
```
to
src/opencensus/proto/agent/metrics/v1/metrics_service_http.yaml
but that'll also require regeneration of the protos of which my protoc compiler has historically radically deviated from @songy23's so kindly also paging @songy23, otherwise I'd send a PR.
